import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className=" min-h-full flex flex-col p-4 justify-between items-center transition duration-1000">
        <ThemeProvider>
          <header className="flex items-center mx-auto max-w-2xl md:max-w-5xl px-4 sm:px-6 lg:px-8 w-full">
            <Header />
          </header>
          <main className="relative flex flex-col justify-center items-center mx-auto w-full max-w-2xl md:max-w-5xl flex-1 p-4 sm:px-6 lg:px-8">
            <div className="absolute inset-0 z-0 bg-[linear-gradient(to_right,var(--border)_1px,transparent_1px),linear-gradient(to_bottom,var(--border)_1px,transparent_1px)] bg-size-[32px_32px] opacity-20 mask-[radial-gradient(ellipse_60%_50%_at_50%_50%,#000_70%,transparent_100%)]" />
            <div className="flex flex-1 flex-col w-full h-full z-10">
              {children}
            </div>
          </main>
          <footer className="flex items-center mx-auto max-w-2xl md:max-w-5xl px-4 sm:px-6 lg:px-8 w-full">
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
